name: Privado Scan
on: push
    
jobs:
  privado:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    env:
      PRIVADO_API_TOKEN: ${{ secrets.PRIVADO_API_TOKEN }}
      PRIVADO_API_ID: "5e3e8b02-5681-4227-951f-6fd7f322d1ea"
      PRIVADO_API_HOST: "https://api.code.privado.ai/prod"
      PRIVADO_CI_PLATFORM: "GITHUB_ACTIONS"
      PRIVADO_DOCKER_IMAGE: 638117407428.dkr.ecr.eu-west-1.amazonaws.com/scanner-agent:latest-dockerless
      PRIVADO_REPOSITORY_ID: ${{ github.repository_id }}
      PRIVADO_REPOSITORY_NAME: ${{ github.repository }}
      PRIVADO_COMMIT_ID: ${{ github.sha }}
      PRIVADO_BRANCH_NAME: ${{ github.ref_name }}
      PRIVADO_DEFAULT_BRANCH_NAME: ${{ github.event.repository.default_branch }}
      PRIVADO_REPOSITORY_URL: ${{ github.repositoryUrl }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Login to docker registry"
      run: |
        curl --fail -s -H "Content-Type: application/json" -H "Authorization: Token $PRIVADO_API_TOKEN" -H "idt: $PRIVADO_API_TOKEN" -H "data-url: /ce/integrations/customers/$PRIVADO_API_ID/docker-registry-token" $PRIVADO_API_HOST/ce/integrations/customers/$PRIVADO_API_ID/docker-registry-token?ci=true | docker login --username AWS --password-stdin $PRIVADO_DOCKER_IMAGE
    - name: Run Privado Scanner
      run: |
        env | grep "PRIVADO_" > $GITHUB_WORKSPACE/.privado.env
        docker run -t -v $GITHUB_WORKSPACE:/privado -v /privado_artefacts:/app/repositories/$PRIVADO_API_ID/$PRIVADO_REPOSITORY_NAME/.privado --env-file $GITHUB_WORKSPACE/.privado.env --privileged --pull=always $PRIVADO_DOCKER_IMAGE
        FAILED_POLICY=$(jq -r '
          .violations[] |
          select(.policyId as $id | ["PrivadoPolicy.Deny.SensitiveSharing", "PrivadoPolicy.Deny.SensitiveLeakage"] | contains([$id])) |
          .policyId
        ' /privado_artefacts/privado.json)
        if [[ -z "${FAILED_POLICY}" ]]; then
            echo "No Issues were found in the scan."
            true
        else
            echo "There was a violation found during the scan : ${FAILED_POLICY}"
            false
        fi
      
